package com.model;
// Generated Jun 7, 2016 8:01:22 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImagesId generated by hbm2java
 */
@Embeddable
public class ImagesId implements java.io.Serializable {

	private int imageId;
	private int productId;

	public ImagesId() {
	}

	public ImagesId(int imageId, int productId) {
		this.imageId = imageId;
		this.productId = productId;
	}

	@Column(name = "imageID", nullable = false)
	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	@Column(name = "productID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImagesId))
			return false;
		ImagesId castOther = (ImagesId) other;

		return (this.getImageId() == castOther.getImageId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImageId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
