package com.model;
// Generated Jun 7, 2016 8:01:22 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images", catalog = "thoitrang")
public class Images implements java.io.Serializable {

	private ImagesId id;
	private Products products;
	private String imageName;
	private String url;

	public Images() {
	}

	public Images(ImagesId id, Products products, String imageName, String url) {
		this.id = id;
		this.products = products;
		this.imageName = imageName;
		this.url = url;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "imageId", column = @Column(name = "imageID", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "productID", nullable = false)) })
	public ImagesId getId() {
		return this.id;
	}

	public void setId(ImagesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productID", nullable = false, insertable = false, updatable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "imageName", nullable = false)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
