package com.model;
// Generated Jun 7, 2016 8:01:22 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Optiongroup generated by hbm2java
 */
@Entity
@Table(name = "optiongroup", catalog = "thoitrang")
public class Optiongroup implements java.io.Serializable {

	private Integer optionGroupId;
	private String optionGroupName;
	private Set<Productoption> productoptions = new HashSet<Productoption>(0);

	public Optiongroup() {
	}

	public Optiongroup(String optionGroupName) {
		this.optionGroupName = optionGroupName;
	}

	public Optiongroup(String optionGroupName, Set productoptions) {
		this.optionGroupName = optionGroupName;
		this.productoptions = productoptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "optionGroupID", unique = true, nullable = false)
	public Integer getOptionGroupId() {
		return this.optionGroupId;
	}

	public void setOptionGroupId(Integer optionGroupId) {
		this.optionGroupId = optionGroupId;
	}

	@Column(name = "optionGroupName", nullable = false)
	public String getOptionGroupName() {
		return this.optionGroupName;
	}

	public void setOptionGroupName(String optionGroupName) {
		this.optionGroupName = optionGroupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optiongroup")
	public Set<Productoption> getProductoptions() {
		return this.productoptions;
	}

	public void setProductoptions(Set<Productoption> productoptions) {
		this.productoptions = productoptions;
	}

}
