package com.model;
// Generated Jun 7, 2016 8:01:22 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productoption generated by hbm2java
 */
@Entity
@Table(name = "productoption", catalog = "thoitrang")
public class Productoption implements java.io.Serializable {

	private Integer productOptionId;
	private Options options;
	private Optiongroup optiongroup;
	private Products products;
	private double optionPriceIncrement;

	public Productoption() {
	}

	public Productoption(Options options, Optiongroup optiongroup, Products products, double optionPriceIncrement) {
		this.options = options;
		this.optiongroup = optiongroup;
		this.products = products;
		this.optionPriceIncrement = optionPriceIncrement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "productOptionID", unique = true, nullable = false)
	public Integer getProductOptionId() {
		return this.productOptionId;
	}

	public void setProductOptionId(Integer productOptionId) {
		this.productOptionId = productOptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optionID", nullable = false)
	public Options getOptions() {
		return this.options;
	}

	public void setOptions(Options options) {
		this.options = options;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optionGroupID", nullable = false)
	public Optiongroup getOptiongroup() {
		return this.optiongroup;
	}

	public void setOptiongroup(Optiongroup optiongroup) {
		this.optiongroup = optiongroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "optionPriceIncrement", nullable = false, precision = 22, scale = 0)
	public double getOptionPriceIncrement() {
		return this.optionPriceIncrement;
	}

	public void setOptionPriceIncrement(double optionPriceIncrement) {
		this.optionPriceIncrement = optionPriceIncrement;
	}

}
