package com.model;
// Generated Jun 7, 2016 8:01:22 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suppliers generated by hbm2java
 */
@Entity
@Table(name = "suppliers", catalog = "thoitrang")
public class Suppliers implements java.io.Serializable {

	private Integer supplierId;
	private String supplierName;
	private String supplierTitle;
	private String address;
	private String city;
	private String region;
	private String phone;
	private String homepage;
	private Set<Products> productses = new HashSet<Products>(0);

	public Suppliers() {
	}

	public Suppliers(String supplierName, String supplierTitle, String address, String city, String region,
			String phone, String homepage) {
		this.supplierName = supplierName;
		this.supplierTitle = supplierTitle;
		this.address = address;
		this.city = city;
		this.region = region;
		this.phone = phone;
		this.homepage = homepage;
	}

	public Suppliers(String supplierName, String supplierTitle, String address, String city, String region,
			String phone, String homepage, Set productses) {
		this.supplierName = supplierName;
		this.supplierTitle = supplierTitle;
		this.address = address;
		this.city = city;
		this.region = region;
		this.phone = phone;
		this.homepage = homepage;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "supplierID", unique = true, nullable = false)
	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "supplierName", nullable = false)
	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	@Column(name = "supplierTitle", nullable = false)
	public String getSupplierTitle() {
		return this.supplierTitle;
	}

	public void setSupplierTitle(String supplierTitle) {
		this.supplierTitle = supplierTitle;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "region", nullable = false)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "homepage", nullable = false)
	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suppliers")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
